spring.application.name=internal_distribution_app_bff
server.servlet.context-path=/
server.port=53400

management.endpoints.access.default=none
management.endpoint.health.access=unrestricted

amazon.dynamodb.endpoint=http://localhost:8000
amazon.aws.accesskey=test
amazon.aws.secretkey=test
amazon.aws.region=us-east-1

# KEYCLOAK
keycloak.base_uri=http://localhost:8080
keycloak.jwt.issuer-uri=${keycloak.base_uri}/realms/${keycloak.realm}
keycloak.client_id=internal_distribution_app
keycloak.client_secret=
keycloak.client_uuid=
keycloak.realm=mi-realm

# Config
keycloak.default-user-rol=user_qa

# Doc
springdoc.api-docs.path=/api-docs